# Generated by Django 2.1 on 2018-08-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='sobrenome',
            new_name='segundo_nome',
        ),
    ]
